### ISSUE TITLE
Doesn't work with Puppeteer

### ISSUE THREAD

**Issue by conradkirschner** [codecept-js/mock-request#2]
I try to mock the page before pageload with puppeteer, but I get a lot of errors and it doesn't mock the page. 

Used with codeceptjs2 - master version. 

```js
    await I.mockRequest('GET', '/', '[]');
    I.mockServer(server => {
        server.any('http://localhost:4200').
        intercept((req, res) => { res.status(200);
        });
    });
    await I.startMocking();
    I.recordMocking();
    I.amOnPage('');

```

```bash
(node:29189) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 294)
(node:29189) UnhandledPromiseRejectionWarning: Error: Request is already handled!
    at assert (/home/conrad-kirschner/WebstormProjects/frontend_ng-web/node_modules/puppeteer/lib/helper.js:283:11)
    at Request.continue (/home/conrad-kirschner/WebstormProjects/frontend_ng-web/node_modules/puppeteer/lib/NetworkManager.js:427:5)
    at Request.<anonymous> (/home/conrad-kirschner/WebstormProjects/frontend_ng-web/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.request (/home/conrad-kirschner/WebstormProjects/frontend_ng-web/node_modules/@pollyjs/adapter-puppeteer/src/index.js:105:11)
    at Page.emit (events.js:323:22)
    at NetworkManager.<anonymous> (/home/conrad-kirschner/WebstormProjects/frontend_ng-web/node_modules/puppeteer/lib/Page.js:110:68)
    at NetworkManager.emit (events.js:323:22)
    at NetworkManager._onRequest (/home/conrad-kirschner/WebstormProjects/frontend_ng-web/node_modules/puppeteer/lib/NetworkManager.js:234:10)
    at NetworkManager._onRequestWillBeSent (/home/conrad-kirschner/WebstormProjects/frontend_ng-web/node_modules/puppeteer/lib/NetworkManager.js:167:14)
    at CDPSession.emit (events.js:311:20)
  -- ASYNC --
    at Request.<anonymous> (/home/conrad-kirschner/WebstormProjects/frontend_ng-web/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.request (/home/conrad-kirschner/WebstormProjects/frontend_ng-web/node_modules/@pollyjs/adapter-puppeteer/src/index.js:105:11)
    at Page.emit (events.js:323:22)
    at NetworkManager.<anonymous> (/home/conrad-kirschner/WebstormProjects/frontend_ng-web/node_modules/puppeteer/lib/Page.js:110:68)
    at NetworkManager.emit (events.js:323:22)
    at NetworkManager._onRequest (/home/conrad-kirschner/WebstormProjects/frontend_ng-web/node_modules/puppeteer/lib/NetworkManager.js:234:10)
    at NetworkManager._onRequestWillBeSent (/home/conrad-kirschner/WebstormProjects/frontend_ng-web/node_modules/puppeteer/lib/NetworkManager.js:167:14)
    at CDPSession.emit (events.js:311:20)
    at CDPSession._onMessage (/home/conrad-kirschner/WebstormProjects/frontend_ng-web/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/home/conrad-kirschner/WebstormProjects/frontend_ng-web/node_modules/puppeteer/lib/Connection.js:112:17)
(node:29189) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 296)


```

**Comment by DavertMik** [comment]
Yeah, looks like Puppeteer in latest releases broke some of their internal API so it's not compatible anymore. While we need time to investigate a fix you can try to downgrade Puppeteer to keep things working

**Comment by Georgegriff** [comment]
Raised here for issue with puppeteer 4.0 https://github.com/Netflix/pollyjs/issues/345

**Comment by taha-ben-masaud1** [comment]
Experiencing a similar issue:

```js
Given("I am on some page", () => {
  I.startMocking("some-page");
  I.amOnPage("/some-page");
  I.waitForInvisible(".loading-screen");
  I.stopMocking();
});
```

#### Context
- codeceptjs: `2.6.7`
- puppeteer: `3.3.0`
- The tests are organised using gherkin.
- I set the mode to `record`.

#### Symptoms
- The page just waits forever. It doesn't freeze.
- When the page enters the forever-waiting phase, and then I use the browser back button and then forward button, `codeceptjs` starts recording and then exists.

**Comment by ydmitry** [comment]
The same with Puppeteer 5.2.1 with Polly and codecept/mock-request

**Comment by conradkirschner** [comment]
I stopped using this polly + mock-request and switched to json-server with some little mock update script... 

But polly is another technique to solve other issues, so if anyone have time to update this package would be awsome

**Comment by RFC2109** [comment]
please update @pollyjs/adapter-puppeteer to "^5.1.0" fix this issue

you may alse need to update @pollyjs/core" 

@DavertMik

**Comment by kobenguyent** [comment]
You may try the mock request built in by Puppeteer helper -> https://codecept.io/puppeteer/#mocking-network-requests
